version: "3.4"

networks:
  kepler_default:
    external: true
services:

  cluster:
    container_name: controller
    image: searcher:v0
    ports:
      - "8610:8610"

    restart: always
    volumes:
      - ./conf/:/controller/searcher/conf/
      - ./logs/:/controller/searcher/logs/

    networks:
      kepler_default: