# before_script:
#   - export GOPATH=$GOPATH:/usr/local/${CI_PROJECT_NAME}
#  - export ABC="some value" # 引入环境变量
#   - cd /usr/local/${CI_PROJECT_NAME}/src/${CI_PROJECT_NAME}
#   - export VERSION=`echo ${CI_COMMIT_TAG} | awk -F"_" '{print $1}'`

# stages
stages:
  - codecheck
  - build
  - unittest
# jobs

check-code:
  stage: codecheck
  script:
    ## 执行makefile文件
    - echo "start check code..."
    - make  -C business    check
    - make  -C scheduler   check
    - make  -C strategy    check
    - make  -C task_tracker check
    # - echo "abc: "$ABC
    #    - make vet
    # - make check
    #- docker run   --env SOURCE_CODE="$PWD"   --volume "$PWD":/code   --volume /var/run/docker.sock:/var/run/docker.sock   registry.gitlab.com/gitlab-org/ci-cd/codequality:${VERSION:-latest} /code

  only:
    - aliyun

build-tags:
  stage: build
  script:
    ## 执行makefile文件
    - echo "start building ..."
    - make  -C business    build
    - make  -C scheduler   build
    - make  -C strategy    build
    - make  -C task_tracker build
  only:
    - aliyun
unit-test:
  stage: unittest
  script:
    - echo "start unit test ..."
    #- make  -C business    test
    - make  -C strategy    test
    #- make  -C task_tracker test
  only:
    - aliyun
